name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "timarabius/platform"
          install: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: src/main/docker/Dockerfile.multistage
          tags: "timarabius/automated-scheduling:latest"
          platforms: linux/amd64
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}

  deploy:
    needs: docker # This ensures deploy runs after build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login registry-1.docker.io -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PAT_READ_ONLY }}
            docker pull timarabius/automated-scheduling:latest
            docker stop scheduling || true
            docker rm scheduling || true
            docker run -p 80:8080 -p 443:8443 -d --name scheduling timarabius/automated-scheduling:latest
